version: '1'
services:
  db:
    image: mongo:latest
    networks:
      - custom
    container_name: test_db
    ports:
      - 27017:27017

  app:
    image: back
    networks:
      - custom
    container_name: test_app
    ports:
      - 8080:3000
    depends_on:
      - db


networks:
  custom:
    driver: bridge
